/*
 * tmu_cfg.c
 *
 * Created: 10/12/2019 7:57:39 PM
 *  Author: omara
 */ 

#include "tmu_cfg.h"



buff buffer [MAXNUMBEROfTASKS] =
{
	{NULL,PERIODIC,5,FINISHED,NA},
			{NULL,PERIODIC,5,FINISHED,NA},
	{NULL,PERIODIC,5,FINISHED,NA},
{NULL,PERIODIC,5,FINISHED,NA},
	{NULL,PERIODIC,5,FINISHED,NA}

//	{NULL,PERIODIC,5,FINISHED},
//	{NULL,PERIODIC,5,FINISHED},
//	{NULL,PERIODIC,5,FINISHED},
//	{NULL,PERIODIC,5,FINISHED},
//	{NULL,PERIODIC,5,FINISHED},
//	{NULL,PERIODIC,5,FINISHED},
//	{NULL,PERIODIC,5,FINISHED},
//	{NULL,PERIODIC,5,FINISHED}
};
